dwm/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('gentelella/', include('gentelella.urls')),
    path('watermarking/', include('watermarking.urls')),
    path('admin/', admin.site.urls),
]

# if the DEBUG is on in settings, then append the urlpatterns as below
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watermarking/urls.py
from django.urls import path
from . import views

app_name = 'watermarking'
urlpatterns = [
    path('', views.index, name='index'),
    path('methods', views.ListWatermarking.as_view(), name='methods'),
    path(
        'detail/<int:pk>/', views.DetailWatermarking.as_view(),
        name='detail'),
    path('newMethod', views.CreateWatermarking.as_view(), name='newMethod'),
    path('coverImages', views.ListCoverImage.as_view(), name='coverImages'),
    path(
        'detail_coverImage/<int:pk>/', views.DetailCoverImage.as_view(),
        name='detail_coverImage'),
    path(
        'newCoverImage', views.CreateCoverImage.as_view(),
        name='newCoverImage'),
    path(
        'watermarkImages', views.ListWatermarkImage.as_view(),
        name='watermarkImages'),
    path(
        'detail_watermarkImage/<int:pk>/', views.DetailWatermarkImage.as_view(),
        name='detail_watermarkImage'),
    path(
        'newWatermarkImage', views.CreateWatermarkImage.as_view(),
        name='newWatermarkImage'),
    path(
        'metrics', views.ListMetric.as_view(),
        name='metrics'),
    path(
        'detail_metric/<int:pk>/', views.DetailMetric.as_view(),
        name='detail_metric'),
    path(
        'newMetric', views.CreateMetric.as_view(),
        name='newMetric'),
    path(
        'noises', views.ListNoise.as_view(),
        name='noises'),
    path(
        'detail_noise/<int:pk>/', views.DetailNoise.as_view(),
        name='detail_noise'),
    path(
        'newNoise', views.CreateNoise.as_view(),
        name='newNoise'),
    path(
        'sprints', views.ListSprintWatermarking.as_view(),
        name='sprints'),
    path(
        'watermarked_result', views.ListMetricSprintWatermarking.as_view(),
        name='watermarked_result'),
    path(
        'watermarked_noised', views.ListNoiseSprintWatermarking.as_view(),
        name='watermarked_noised'),
    path(
        'watermark_result', views.ListMetricNoiseSprintWatermarking.as_view(),
        name='watermark_result'),
    path(
        'imageTypes', views.ListImageType.as_view(),
        name='imageTypes'),
    path(
        'newImageType', views.CreateImageType.as_view(),
        name='newImageType'),
]

watermarking/forms.py
# -*- encoding:utf-8 -*-
# -*- coding:utf-8 -*-
from django import forms
from .models import (
    Watermarking, CoverImage, WatermarkImage, Metric, Noise, ImageType)

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field
from crispy_forms.bootstrap import (
    PrependedText, PrependedAppendedText, FormActions)


class BtnsSubmitCancelMixing(object):
    helper = FormHelper()
    helper.add_input(Submit('submit', 'Submit', css_class='btn-primary'))
    helper.add_input(Submit(
        'cancel', 'Cancel', css_class='btn-danger',
        formnovalidate='formnovalidate',))
    helper.form_method = 'POST'


class WatermarkingForm(BtnsSubmitCancelMixing, forms.ModelForm):
    class Meta:
        model = Watermarking
        fields = '__all__'


class CoverImageForm(BtnsSubmitCancelMixing, forms.ModelForm):
    class Meta:
        model = CoverImage
        fields = ['name', 'cover_image', 'image_type']


class WatermarkImageForm(BtnsSubmitCancelMixing, forms.ModelForm):
    class Meta:
        model = WatermarkImage
        fields = ['name', 'watermark_image', 'image_type']


class MetricForm(BtnsSubmitCancelMixing, forms.ModelForm):
    class Meta:
        model = Metric
        fields = '__all__'


class NoiseForm(BtnsSubmitCancelMixing, forms.ModelForm):
    class Meta:
        model = Noise
        fields = ['name', 'source_code']


class ImageTypeForm(BtnsSubmitCancelMixing, forms.ModelForm):
    class Meta:
        model = ImageType
        fields = "__all__"

watermarking/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponseRedirect

from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import (
    CreateView, DeleteView, FormView, UpdateView)

from .models import (
    Watermarking, CoverImage, WatermarkImage, Metric, Noise,
    SprintWatermarking, MetricSprintWatermarking, NoiseSprintWatermarking,
    MetricNoiseSprintWatermarking, ImageType)

from .forms import (
    WatermarkingForm, CoverImageForm, WatermarkImageForm, MetricForm,
    NoiseForm, ImageTypeForm)

from .task import mainTask


def index(request):
    return render(request, 'watermarking/index.html')


# Watermarking Views
class ListWatermarking(ListView):
    template_name = 'watermarking/lists/list_Watermarking.html'

    def get_queryset(self):
        """Return the watermarking methods."""
        return Watermarking.objects.all()


class DetailWatermarking(DetailView):
    model = Watermarking
    template_name = 'watermarking/details/detail_Watermarking.html'


class FormActionMixin(object):

    def post(self, request, *args, **kwargs):
        """Add 'Cancel' button redirect."""
        if "cancel" in request.POST:
            return HttpResponseRedirect(self.success_url)
        else:
            return super(FormActionMixin, self).post(request, *args, **kwargs)


class CreateWatermarking(FormActionMixin, CreateView):

    model = Watermarking
    template_name = "watermarking/create/create_Watermarking.html"
    success_url = reverse_lazy("watermarking:methods")
    form_class = WatermarkingForm

    def form_valid(self, form):
        watermarking = form.save(commit=False)
        try:
            watermarking.save()
            mainTask.delay()
            return super(CreateWatermarking, self).form_valid(form)
        except Exception as e:
            form.add_error(None, e)

        return super(CreateWatermarking, self).form_invalid(form)


# Cover Image Views
class ListCoverImage(ListView):
    template_name = 'watermarking/lists/list_CoverImage.html'

    def get_queryset(self):
        """Return the watermarking methods."""
        return CoverImage.objects.all()


class DetailCoverImage(DetailView):
    model = CoverImage
    template_name = 'watermarking/details/detail_CoverImage.html'


class CreateCoverImage(FormActionMixin, CreateView):

    model = CoverImage
    template_name = "watermarking/create/create_CoverImage.html"
    success_url = reverse_lazy("watermarking:coverImages")
    form_class = CoverImageForm

    def form_valid(self, form):
        coverImage = form.save(commit=False)
        try:
            coverImage.save()
            mainTask.delay()
            return super(CreateCoverImage, self).form_valid(form)
        except Exception as e:
            form.add_error(None, e)

        return super(CreateCoverImage, self).form_invalid(form)


# Watermark Image Views
class ListWatermarkImage(ListView):
    template_name = 'watermarking/lists/list_WatermarkImage.html'

    def get_queryset(self):
        """Return the watermarking methods."""
        return WatermarkImage.objects.all()


class DetailWatermarkImage(DetailView):
    model = WatermarkImage
    template_name = 'watermarking/details/detail_WatermarkImage.html'


class CreateWatermarkImage(FormActionMixin, CreateView):

    model = WatermarkImage
    template_name = "watermarking/create/create_WatermarkImage.html"
    success_url = reverse_lazy("watermarking:watermarkImages")
    form_class = WatermarkImageForm

    def form_valid(self, form):
        coverImage = form.save(commit=False)
        try:
            coverImage.save()
            mainTask.delay()
            return super(CreateWatermarkImage, self).form_valid(form)
        except Exception as e:
            form.add_error(None, e)

        return super(CreateWatermarkImage, self).form_invalid(form)


# Metrics Views
class ListMetric(ListView):
    template_name = 'watermarking/lists/list_Metric.html'

    def get_queryset(self):
        """Return metrics."""
        return Metric.objects.all()


class DetailMetric(DetailView):
    model = Metric
    template_name = 'watermarking/details/detail_Metric.html'


class CreateMetric(FormActionMixin, CreateView):

    model = Metric
    template_name = "watermarking/create/create_Metric.html"
    success_url = reverse_lazy("watermarking:metrics")
    form_class = MetricForm

    def form_valid(self, form):
        metric = form.save(commit=False)
        try:
            metric.save()
            mainTask.delay()
            return super(CreateMetric, self).form_valid(form)
        except Exception as e:
            form.add_error(None, e)
        return super(CreateMetric, self).form_invalid(form)


# Noise Views
class ListNoise(ListView):
    template_name = 'watermarking/lists/list_Noise.html'

    def get_queryset(self):
        """Return noises."""
        return Noise.objects.all()


class DetailNoise(DetailView):
    model = Noise
    template_name = 'watermarking/details/detail_Noise.html'


class CreateNoise(FormActionMixin, CreateView):

    model = Noise
    template_name = "watermarking/create/create_Noise.html"
    success_url = reverse_lazy("watermarking:noises")
    form_class = NoiseForm

    def form_valid(self, form):
        noise = form.save(commit=False)
        try:
            noise.save()
            mainTask.delay()
            return super(CreateNoise, self).form_valid(form)
        except Exception as e:
            form.add_error(None, e)
        return super(CreateNoise, self).form_invalid(form)


# Sprint Watermarking Views
class ListSprintWatermarking(ListView):
    template_name = 'watermarking/lists/list_SprintWatermarking.html'

    def get_queryset(self):
        """Return sprints."""
        return SprintWatermarking.objects.all()


# Metric Sprint Watermarking Views
class ListMetricSprintWatermarking(ListView):
    template_name = 'watermarking/lists/list_MetricSprintWatermarking.html'

    def get_queryset(self):
        """Return metric sprint."""
        return MetricSprintWatermarking.objects.all().order_by(
            'metric', '-value')


# Metric Sprint Watermarking Views
class ListNoiseSprintWatermarking(ListView):
    template_name = 'watermarking/lists/list_NoiseSprintWatermarking.html'

    def get_queryset(self):
        """Return noised sprint."""
        return NoiseSprintWatermarking.objects.all().order_by(
            'sprintWatermarking')


# Metric Noise Sprint Watermarking Views
class ListMetricNoiseSprintWatermarking(ListNoiseSprintWatermarking):
    template_name = 'watermarking/lists/list_MetricNoiseSprintWatermarking.html'


# Image Type Views
class ListImageType(ListView):
    template_name = 'watermarking/lists/list_ImageType.html'

    def get_queryset(self):
        """Return image types."""
        return ImageType.objects.all()


class CreateImageType(FormActionMixin, CreateView):

    model = ImageType
    template_name = "watermarking/create/create_ImageType.html"
    success_url = reverse_lazy("watermarking:imageTypes")
    form_class = ImageTypeForm

    def form_valid(self, form):
        imageType = form.save(commit=False)
        try:
            imageType.save()
            return super(CreateImageType, self).form_valid(form)
        except Exception as e:
            form.add_error(None, e)
        return super(CreateImageType, self).form_invalid(form)

watermarking/templates/watermarking/lists/list_CoverImage.html
{% extends 'core/base.html' %}

{% block header %} Cover Images {% endblock header %}

{% block title %} Media Gallery {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3> Cover Image Gallery </h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li>
                  <a class="btn btn-xs" href="{% url 'watermarking:newCoverImage' %}" data-rel="tooltip" data-original-title="New cover image" title="">
                      <i class="ace-icon fa fa-plus bigger-120"> Add </i>
                  </a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">

              <div class="row">

                {% for cover in object_list %}

                    <div class="col-md-55">
                      <div class="thumbnail">
                        <div class="image view view-first">
                          <img style="width: 100%; display: block;" src="/media/{{cover.cover_image}}" alt="image" />
                          <div class="mask no-caption">
                            <div class="tools tools-bottom">
                              <a href="#"><i class="fa fa-link"></i></a>
                              <a href="#"><i class="fa fa-pencil"></i></a>
                              <a href="#"><i class="fa fa-times"></i></a>
                            </div>
                          </div>
                        </div>
                        <div class="caption">
                          <p><strong>{{cover.name}}</strong>
                          </p>
                          <p>2018 used</p>
                        </div>
                      </div>
                    </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}

watermarking/templates/watermarking/lists/list_ImageType.html
{% extends 'core/base.html' %}

{% block title %} Image Types {% endblock title %}

{% block header %} Image Types {% endblock header %}

{% block stylesheets %}
  {{ block.super }}
  {% load static %}
  <link href="{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Image Types</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">

            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li>
                  <a class="btn btn-xs" href="{% url 'watermarking:newImageType' %}" data-rel="tooltip" data-original-title="New type" title="">
                      <i class="ace-icon fa fa-plus bigger-120"> Add </i>
                  </a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>

            <div class="x_content">

              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Description</th>
                  </tr>
                </thead>

                {% for n in object_list %}
                <tr>
                    <td>{{ n.name }}</td>
                    <td>{{ n.description }}</td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="{% static "vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.flash.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.print.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-keytable/js/dataTables.keyTable.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-responsive/js/dataTables.responsive.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js" %}"></script>
  <script src="{% static "vendors/datatables.net-scroller/js/dataTables.scroller.min.js" %}"></script>
  <script src="{% static "vendors/jszip/dist/jszip.min.js" %}"></script>
  <script src="{% static "vendors/pdfmake/build/pdfmake.min.js" %}"></script>
  <script src="{% static "vendors/pdfmake/build/vfs_fonts.js" %}"></script>
{% endblock javascripts %}

watermarking/templates/watermarking/lists/list_Metric.html
{% extends 'core/base.html' %}

{% block title %} Metrics {% endblock title %}

{% block header %} Metrics {% endblock header %}

{% block stylesheets %}
  {{ block.super }}
  {% load static %}
  <link href="{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Metrics</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">

            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li>
                  <a class="btn btn-xs" href="{% url 'watermarking:newMetric' %}" data-rel="tooltip" data-original-title="New watermarking" title="">
                      <i class="ace-icon fa fa-plus bigger-120"> Add </i>
                  </a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>

            <div class="x_content">

              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Upload at</th>
                    <th>Source code</th>
                  </tr>
                </thead>

                {% for w in object_list %}
                <tr>
                    <td>{{ w.name }}</td>
                    <td>{{ w.uploaded_at }}</td>
                    <td>{{ w.source_code }}</td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="{% static "vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.flash.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.print.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-keytable/js/dataTables.keyTable.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-responsive/js/dataTables.responsive.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js" %}"></script>
  <script src="{% static "vendors/datatables.net-scroller/js/dataTables.scroller.min.js" %}"></script>
  <script src="{% static "vendors/jszip/dist/jszip.min.js" %}"></script>
  <script src="{% static "vendors/pdfmake/build/pdfmake.min.js" %}"></script>
  <script src="{% static "vendors/pdfmake/build/vfs_fonts.js" %}"></script>
{% endblock javascripts %}

watermarking/templates/watermarking/lists/list_Noise.html
{% extends 'core/base.html' %}

{% block title %} Noises {% endblock title %}

{% block header %} Noises {% endblock header %}

{% block stylesheets %}
  {{ block.super }}
  {% load static %}
  <link href="{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" %}" rel="stylesheet">
  <link href="{% static "vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" %}" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Noises</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">

            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li>
                  <a class="btn btn-xs" href="{% url 'watermarking:newNoise' %}" data-rel="tooltip" data-original-title="New watermarking" title="">
                      <i class="ace-icon fa fa-plus bigger-120"> Add </i>
                  </a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>

            <div class="x_content">

              <table id="datatable-buttons" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Upload at</th>
                    <th>Source code</th>
                  </tr>
                </thead>

                {% for n in object_list %}
                <tr>
                    <td>{{ n.name }}</td>
                    <td>{{ n.uploaded_at }}</td>
                    <td>{{ n.source_code }}</td>
                </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
  <!-- Datatables -->
  <script src="{% static "vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.flash.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-buttons/js/buttons.print.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-keytable/js/dataTables.keyTable.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-responsive/js/dataTables.responsive.min.js" %}"></script>
  <script src="{% static "vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js" %}"></script>
  <script src="{% static "vendors/datatables.net-scroller/js/dataTables.scroller.min.js" %}"></script>
  <script src="{% static "vendors/jszip/dist/jszip.min.js" %}"></script>
  <script src="{% static "vendors/pdfmake/build/pdfmake.min.js" %}"></script>
  <script src="{% static "vendors/pdfmake/build/vfs_fonts.js" %}"></script>
{% endblock javascripts %}

watermarking/templates/watermarking/lists/list_WatermarkImage.html
{% extends 'core/base.html' %}

{% block header %} Watermark Images {% endblock header %}

{% block title %} Watermark Images {% endblock title %}

{% block stylesheets %}
  {{ block.super }}
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3> Watermark Image Gallery </h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12">
          <div class="x_panel">
            <div class="x_title">
              <ul class="nav navbar-right panel_toolbox">
                <li>
                  <a class="btn btn-xs" href="{% url 'watermarking:newWatermarkImage' %}" data-rel="tooltip" data-original-title="New cover image" title="">
                      <i class="ace-icon fa fa-plus bigger-120"> Add </i>
                  </a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">

              <div class="row">

                {% for watermark in object_list %}

                    <div class="col-md-55">
                      <div class="thumbnail">
                        <div class="image view view-first">
                          <img style="width: 100%; display: block;" src="/media/{{watermark.watermark_image}}" alt="image" />
                          <div class="mask no-caption">
                            <div class="tools tools-bottom">
                              <a href="#"><i class="fa fa-link"></i></a>
                              <a href="#"><i class="fa fa-pencil"></i></a>
                              <a href="#"><i class="fa fa-times"></i></a>
                            </div>
                          </div>
                        </div>
                        <div class="caption">
                          <p><strong>{{watermark.name}}</strong>
                          </p>
                          <p>2018 used</p>
                        </div>
                      </div>
                    </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super }}
{% endblock javascripts %}