core/urls.py
# -*- encoding:utf-8 -*-
# -*- coding:utf-8 -*-
from django.urls import path
from django.contrib import admin
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    # url(r'^index/$', index, name='index'),
    path('logout', views.logout, name='logout'),
    path('cambiar_passwd', views.cambiar_passwd, name='cambiar_passwd'),
    path('uploads_simple', views.simple_upload, name='simple_upload'),
    # path('uploads_form/$', views.model_form_upload, name='model_form_upload'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dwm/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('gentelella/', include('gentelella.urls')),
    path('watermarking/', include('watermarking.urls')),
    path('admin/', admin.site.urls),
]

# if the DEBUG is on in settings, then append the urlpatterns as below
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

watermarking/urls.py
from django.urls import path
from . import views

app_name = 'watermarking'
urlpatterns = [
    path('', views.index, name='index'),
    path('methods', views.ListWatermarking.as_view(), name='methods'),
    path(
        'detail/<int:pk>/', views.DetailWatermarking.as_view(),
        name='detail'),
    path('newMethod', views.CreateWatermarking.as_view(), name='newMethod'),
    path('coverImages', views.ListCoverImage.as_view(), name='coverImages'),
    path(
        'detail_coverImage/<int:pk>/', views.DetailCoverImage.as_view(),
        name='detail_coverImage'),
    path(
        'newCoverImage', views.CreateCoverImage.as_view(),
        name='newCoverImage'),
    path(
        'watermarkImages', views.ListWatermarkImage.as_view(),
        name='watermarkImages'),
    path(
        'detail_watermarkImage/<int:pk>/', views.DetailWatermarkImage.as_view(),
        name='detail_watermarkImage'),
    path(
        'newWatermarkImage', views.CreateWatermarkImage.as_view(),
        name='newWatermarkImage'),
    path(
        'metrics', views.ListMetric.as_view(),
        name='metrics'),
    path(
        'detail_metric/<int:pk>/', views.DetailMetric.as_view(),
        name='detail_metric'),
    path(
        'newMetric', views.CreateMetric.as_view(),
        name='newMetric'),
    path(
        'noises', views.ListNoise.as_view(),
        name='noises'),
    path(
        'detail_noise/<int:pk>/', views.DetailNoise.as_view(),
        name='detail_noise'),
    path(
        'newNoise', views.CreateNoise.as_view(),
        name='newNoise'),
    path(
        'sprints', views.ListSprintWatermarking.as_view(),
        name='sprints'),
    path(
        'watermarked_result', views.ListMetricSprintWatermarking.as_view(),
        name='watermarked_result'),
    path(
        'watermarked_noised', views.ListNoiseSprintWatermarking.as_view(),
        name='watermarked_noised'),
    path(
        'watermark_result', views.ListMetricNoiseSprintWatermarking.as_view(),
        name='watermark_result'),
    path(
        'imageTypes', views.ListImageType.as_view(),
        name='imageTypes'),
    path(
        'newImageType', views.CreateImageType.as_view(),
        name='newImageType'),
]

core/models.py
# -*- encoding:utf-8 -*-
# -*- coding:utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

core/forms.py
# -*- encoding:utf-8 -*-
# -*- coding:utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput


class CambiarPasswdForm(forms.Form):

    passwd_actual = forms.CharField(label='Contraseña actual', widget=forms.PasswordInput)
    nuevo_passwd = forms.CharField(label='Nueva contraseña', widget=forms.PasswordInput)
    conf_nuevo_passwd = forms.CharField(label='Confirmar nueva contraseña', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(CambiarPasswdForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean_conf_nuevo_passwd(self):
        nuevo_passwd = self.cleaned_data.get('nuevo_passwd')
        conf_nuevo_passwd = self.cleaned_data.get('conf_nuevo_passwd')
        if nuevo_passwd and conf_nuevo_passwd and nuevo_passwd != conf_nuevo_passwd:
            raise forms.ValidationError('Las contraseñas no coinciden')
        return conf_nuevo_passwd

core/views.py
# -*- encoding:utf-8 -*-
# -*- coding:utf-8 -*-
from django.shortcuts import (
    render_to_response, HttpResponse, HttpResponseRedirect)
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import redirect_to_login
from datetime import datetime
from django.urls import reverse, resolve
from django.contrib import auth
from .forms import CambiarPasswdForm
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.contrib.auth.hashers import check_password
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.utils.six.moves.urllib.parse import urlparse
from django.conf import settings

from django.shortcuts import render, redirect

from django.core.files.storage import FileSystemStorage


def index(request):
    return render(request, 'core/index.html')


# Vista de login
def login(request):
    if request.method == 'POST':
        try:
            referer = request.META['HTTP_REFERER']
            # url para el redirecionamiento después de loguearse desde una
            # página que no requiere loguearse
            query = urlparse(referer)[4]
            if query:
                url = query.partition('=')[2]
            else:
                url = urlparse(referer)[2]
        except KeyError:
            url = settings.LOGIN_URL

        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
        else:
            messages.error(request, 'Credenciales incorrectas, por favor intente nuevamente.')

        return HttpResponseRedirect(url)
    else:
        return HttpResponseRedirect(settings.LOGIN_URL)


@login_required(login_url="core:login")
def logout(request):
    auth.logout(request)
    next = request.GET['next']
    return HttpResponseRedirect(next)


# Yusdanis Feus Pérez
@login_required(login_url="core:login")
def cambiar_passwd(request):

    if request.POST:
        form = CambiarPasswdForm(request.POST)
        if form.is_valid():
            usuario = User.objects.get(username=request.user.username)
            pass_actual = form.cleaned_data['passwd_actual']
            pass_nuevo = form.cleaned_data['nuevo_passwd']

            if check_password(pass_actual, usuario.password):
                if check_password(pass_nuevo, usuario.password):
                    form.add_error(None, "La nueva contraseña es igual a la actual.")
                    return render_to_response("cambiar_passwd.html", {'form': form}, context_instance=RequestContext(request))
                else:
                    usuario.set_password(pass_nuevo)
                    usuario.save()
                    update_session_auth_hash(request, usuario)
                    messages.add_message(request, messages.INFO, 'Contraseña actualizada satisfacotiamente.')
            else:
                form.add_error(None, "Contraseña actual incorrecta, intente nuevamente.")
                return render_to_response("cambiar_passwd.html", {'form': form}, context_instance=RequestContext(request))
        else:
            return render_to_response("cambiar_passwd.html", {'form': form}, context_instance=RequestContext(request))

    form = CambiarPasswdForm()

    return render_to_response("cambiar_passwd.html", {'form': form}, context_instance=RequestContext(request))


def simple_upload(request):
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        return render(request, 'core/simple_upload.html', {
            'uploaded_file_url': uploaded_file_url
        })
    return render(request, 'core/simple_upload.html')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    {% block head %}
      {% block meta %}
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock meta %}

      <title>Data Hiding Methods in Digital Images | {% block title %}{% endblock %}</title>

      {% block stylesheets %}
        <!-- Bootstrap -->
        <link href="{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="{% static "vendors/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
        <!-- NProgress -->
        <link href="{% static "vendors/nprogress/nprogress.css" %}" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <link href="{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}" rel="stylesheet">
        <!-- iCheck -->
        <link href="{% static "vendors/iCheck/skins/flat/green.css" %}" rel="stylesheet">
        <!-- bootstrap-progressbar -->
        <link href="{% static "vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" %}" rel="stylesheet">
        <!-- JQVMap -->
        <link href="{% static "vendors/jqvmap/dist/jqvmap.min.css" %}" rel="stylesheet"/>
      {% endblock stylesheets %}
      <!-- Custom Theme Style -->
      <link href="{% static "build/css/custom.css" %}" rel="stylesheet">
    {% endblock head %}
  </head>

  <body class="{% block body_class %}nav-md {% endblock body_class %}">
    {% block body %}
      <div class="container body">
        <div class="main_container">

          {% block top_navigation %}
            <div class="top_nav">
              {% include "gentelella/top_navigation.html" %}
            </div>
          {% endblock top_navigation %}

          {% block sidebar %}
            <div class="col-md-3 left_col {% block sidebar_class %} {% endblock sidebar_class %}">
              {% include "core/sidebar.html" %}
            </div>
          {% endblock sidebar %}

          {% block content %}
              Contenido de la p&aacute;gina de inicio
          {% endblock content %}

          {% block footer %}
            <footer>
              {% include "core/footer.html" %}
            </footer>
          {% endblock footer %}
        </div>
      </div>

      {% block javascripts %}
        <!-- jQuery -->
        <script src="{% static "vendors/jquery/dist/jquery.min.js" %}"></script>
        <!-- Bootstrap -->
        <script src="{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}"></script>
        <!-- FastClick -->
        <script src="{% static "vendors/fastclick/lib/fastclick.js" %}"></script>
        <!-- NProgress -->
        <script src="{% static "vendors/nprogress/nprogress.js" %}"></script>
        <!-- bootstrap-progressbar -->
        <script src="{% static "vendors/bootstrap-progressbar/bootstrap-progressbar.min.js" %}"></script>
        <!-- iCheck -->
        <script src="{% static "vendors/iCheck/icheck.min.js" %}"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="{% static "vendors/moment/min/moment.min.js" %}"></script>
        <script src="{% static "vendors/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
        <!-- bootstrap-wysiwyg -->
        <script src="{% static "vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js" %}"></script>
        <script src="{% static "vendors/jquery.hotkeys/jquery.hotkeys.js" %}"></script>
        <script src="{% static "vendors/google-code-prettify/src/prettify.js" %}"></script>
        <!-- jQuery Tags Input -->
        <script src="{% static "vendors/jquery.tagsinput/src/jquery.tagsinput.js" %}"></script>
        <!-- Switchery -->
        <script src="{% static "vendors/switchery/dist/switchery.min.js" %}"></script>
        <!-- Select2 -->
        <script src="{% static "vendors/select2/dist/js/select2.full.min.js" %}"></script>
        <!-- Parsley -->
        <script src="{% static "vendors/parsleyjs/dist/parsley.min.js" %}"></script>
        <!-- Autosize -->
        <script src="{% static "vendors/autosize/dist/autosize.min.js" %}"></script>
        <!-- jQuery autocomplete -->
        <script src="{% static "vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js" %}"></script>
        <!-- starrr -->
        <script src="{% static "vendors/starrr/dist/starrr.js" %}"></script>
      {% endblock %}
      <!-- Custom Theme Scripts -->
      <script src="{% static "build/js/custom.js" %}"></script>
    {% endblock body %}
  </body>
</html>



{% block page_js %}
{% endblock page_js %}

core/templates/core/base_list.html
{% extends 'core/base.html'%}

{% block titulo %}{% endblock titulo %}

{% block header %}{% endblock header %}

{% block menu_vertical %}{% endblock menu_vertical %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="clearfix">
                {% for message in messages %}
                <div class="alert alert-block alert-success">
                    <button type="button" class="close" data-dismiss="alert">
                            <i class="ace-icon fa fa-times"></i>
                    </button>
                    <p>
                        <i class="ace-icon fa fa-exclamation-circle"></i>
                        {{ message }}
                    </p>
                </div>
                {% endfor %}

                {% block nota_tabla %} {% endblock nota_tabla %}

                {% block filtro_tabla %} {% endblock filtro_tabla %}

                <div class="pull-right tableTools-container">
                    <div class="btn-group btn-overlap">
                        {% block botones_tabla %} {% endblock botones_tabla %}
                    </div>
                </div>
             </div>

            {% if object_list %}
                <div class="table-header">
                {% block titulo_tabla %}{% endblock titulo_tabla %}
                </div>

                <div>
                    <table id="dynamic-table" class="table table-striped table-bordered table-hover">
                        <thead>
                            {% block head_tabla %}{% endblock head_tabla %}
                        </thead>
                        <tbody>
                            {% block body_tabla %}{% endblock body_tabla %}
                        </tbody>
                    </table>
                </div>
            {% else %}
            <div class="alert alert-block alert-success" style="margin-top: 20px; width:60%">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>
                <p>
                    <i class="ace-icon fa fa-exclamation-circle "></i>
                    No hay resultados para mostrar.
                </p>
            </div>
            {% endif %}
        </div>
    </div>

     <!-- Dialog para confirmación de eliminación -->
    <div id="dialog-confirm" class="hide">
        <div class="alert alert-info bigger-110" id="modal-body">
            <!-- texto -->
        </div>

        <div class="space-6"></div>

        <p class="bigger-110 bolder center grey">
            <i class="ace-icon fa fa-hand-o-right blue bigger-120"></i>
            Esta acci&oacute;n no podr&aacute; deshacerse.
        </p>
    </div>

    <!-- Dialog para detalles -->
    <div id="dialog-details" class="hide">
      <div>
          <table id="dynamic-table" class="table table-striped  table-hover">
            <tbody></tbody>
          </table>
      </div>
    </div>
{% endblock content %}


{% block page_js %}
    {% load static %}
    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "js/jquery.dataTables.bootstrap.min.js" %}"></script>

    {% block page_scripts %}{% endblock page_scripts %}
{% endblock page_js %}

{% block jquery_conf %}
    // Para los tooltips
    $('[data-rel=tooltip]').tooltip();
    $('[data-rel=popover]').popover({html: true});

    //initiate dataTables plugin
    $('#dynamic-table').dataTable({
        "scrollX": true,
        responsive: true,
        bAutoWidth: false,
        bSort:false,
        enableFiltering: false
    });
{% endblock jquery_conf %}

core/templates/core/cambiar_passwd.html
{% extends 'base.html' %}

{% block titulo %} Cambiar contrase&ntilde;a {% endblock titulo %}

{% block header %} Cambiar contrase&ntilde;a {% endblock header %}

{% block contenido %}

<div class="row">
    <div class="col-md-4 col-sm-4 col-xs-4">
        {% for message in messages %}
            <div class="alert alert-block alert-success">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>
                <p>                    
                    <i class="ace-icon fa fa-exclamation-circle"></i>
                    {{ message }}               
                </p>
            </div>
        {% endfor %}
        
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">
                    <i class="ace-icon fa fa-times"></i>
                </button>

                <p>                   
                    <i class="ace-icon fa fa-exclamation-triangle"></i>
                    {{ error }}                
                </p>
            </div>
        {% endfor %}
        
        <div class="panel panel-primary">
            <div class="panel-heading"> Entre los datos de la nueva contrase&ntilde;a</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-10">
                            <form method="POST" action="">{% csrf_token %}
                                {% for campo in form %}
                                    <div class="form-group">
                                        <label>{{ campo.label }}</label> {{ campo }}
                                        {% for error in campo.errors %}
                                            <div class="alert alert-danger">
                                                <button type="button" class="close" data-dismiss="alert">
                                                    <i class="ace-icon fa fa-times"></i>
                                                </button>

                                                <p>
                                                    <i class="ace-icon fa fa-exclamation-triangle"></i>
                                                    {{ error|lower|capfirst  }}
                                                </p>
                                            </div>
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                                <button id="finalizar" class="btn btn-blue btn-primary btn-round">
                					<i class="ace-icon fa fa-check bigger-110"></i>
                					Finalizar									
								</button>
                                <button class="btn btn-grey btn-primary btn-round" type="reset">
                					<i class="ace-icon fa fa-undo bigger-110"></i>
                					Reiniciar									
								</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock contenido %}

core/templates/core/footer.html
<div class="pull-right">
  Data Hiding Methods in Digital Image - Development by <a href="http://10.25.45.204:8010/">Tecnology Departament of Granma University</a>
</div>
<div class="clearfix"></div>

core/templates/core/login.html
<div style="margin-top: 5px; text-align: center">
<form id="login_form" method="post" action="{% url 'core:login' %}?next={{ request.path }}" class="width-100">{% csrf_token %}
    <span class="input-icon align-bottom" style="margin-right: 5px;line-height: 1.2">
        <input type="text" name="username" placeholder="User" size="12"  style="font-size: 13px;" />
        <i class="ace-icon fa fa-user" style="top: 0"></i>
    </span>

    <span class="input-icon align-bottom" style="margin-right: 5px;line-height: 1.2">
        <input type="password" name="password"  placeholder="Password" size="12" style="font-size: 13px" />
        <i class="ace-icon fa fa-lock" style="top: 0"></i>
    </span>
    <button type="submit" class="btn btn-sm btn-primary" style="padding:5px 9px;border:1px solid #2a62bc">
         <span> Login </span>
    </button>
</form>

<!-- Si hay error -->
{% if messages %}
<p class="alert-danger" style="position:absolute;font-size: 12px;border-radius: 4px; padding: 4px;margin-top: 3px;border: 1px solid #b03911">
    {% for message in messages %}
    <i class="ace-icon fa fa-exclamation-triangle"></i>
    {{ message|lower|capfirst  }}
    {% endfor %}
</p>
{% endif %}
</div>

core/templates/core/menu_principal.html
{% load static%}

<ul class="nav nav-list">

    <!-- MÓDULO WATERMARKING -->
    {% if modulo == 'watermarking' %} <li class="active hover">{% else %} <li class="hover"> {% endif %}
        <a href="{% url 'watermarking:index' %}">
            <i class="menu-icon fa ">
               <img src="{% static "core/icons/watermark.png" %}" height=30 width=30/>
            </i>
            <span class="menu-text"> Watermarking </span>
        </a>

        <b class="arrow"></b>
    </li>
    <!-- /MÓDULO WATERMARKING -->
    <!-- MÓDULO STEGANOGRAFÍA -->
    {% if modulo == 'steganography' %} <li class="active hover">{% else %} <li class="hover"> {% endif %}
        <a href="">
            <i class="menu-icon fa ">
               <img src="{% static "core/icons/steganography.png" %}" height=30 width=30/>
            </i>
            <span class="menu-text"> Steganography </span>
        </a>

        <b class="arrow"></b>
    </li>
    <!-- /MÓDULO STEGANOGRAFÍA -->

    <!-- MÓDULO DE ADMINISTRACIÓN -->
    {% if modulo == 'administracion' %} <li class="active hover"> {% else %} <li class="hover">	{% endif %}
        <!--<a href="#">
            <i class="menu-icon fa fa-cog"></i>
            <span class="menu-text"> Administraci&oacute;n </span>
        </a>

        <b class="arrow"></b>-->
    </li>
    <!-- /MÓDULO DE ADMINISTRACIÓN -->
</ul>

core/templates/core/sidebar.html
{% load static %}

<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
    <a href="{% url 'watermarking:index' %}" class="site_title">
      <i class="menu-icon">
       <img src="{% static 'core/images/watermarking_icono.png' %}" />
      </i> <span>DHMDI</span>
    </a>
  </div>

  <div class="clearfix"></div>

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/datahiding_icono.png' %}" />
        </i> Image Types <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'watermarking:imageTypes' %}">Image Types</a></li>
          </ul>
        </li>
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/datahiding_icono.png' %}" />
          </i> Cover Images <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'watermarking:coverImages' %}">Gallery</a></li>
          </ul>
        </li>
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/datahiding_icono.png' %}" />
        </i> Watermark Images <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'watermarking:watermarkImages' %}">Gallery</a></li>
          </ul>
        </li>
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/datahiding_icono.png' %}" />
        </i> Metrics <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'watermarking:metrics' %}">List</a></li>
          </ul>
        </li>
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/datahiding_icono.png' %}" />
            </i> Noises <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'watermarking:noises' %}">List</a></li>
          </ul>
        </li>
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/datahiding_icono.png' %}" />
        </i> Download Template <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% static 'watermarking/insert.py' %}">Insert Method</a></li>
            <li><a href="{% static 'watermarking/extract.py' %}">Extract Method</a></li>
            <li><a href="{% static 'watermarking/metric.py' %}">Metric</a></li>
            <li><a href="{% static 'watermarking/noise.py' %}">Noise</a></li>
            <li><a>
                <i class="menu-icon">
                <img src="{% static 'core/images/datahiding_icono.png' %}" />
              </i> Metrics <span class="fa fa-chevron-down"></span></a>
                <ul class="nav child_menu">
                  <li><a href="{% static 'watermarking/metrics/PSNR.py' %}">PSNR</a></li>
                  <li><a href="{% static 'watermarking/metrics/BER.py' %}">BER</a></li>
                </ul>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="menu_section">
      <h3>Watermarking</h3>
      <ul class="nav side-menu">
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/watermarking_icono.png' %}" />
          </i> Methods <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="{% url 'watermarking:methods' %}">List</a></li>
            <li><a href="{% url 'watermarking:watermarked_result' %}">Watermarked Result</a></li>
            <li><a href="{% url 'watermarking:watermarked_noised' %}">Watermarked Noise</a></li>
            <li><a href="{% url 'watermarking:watermark_result' %}">Watermark Result</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- <div class="menu_section">
      <h3>Steganography</h3>
      <ul class="nav side-menu">
        <li><a>
          <i class="menu-icon">
          <img src="{% static 'core/images/DH_icono.png' %}" />
          </i> Methods <span class="fa fa-chevron-down"></span></a>
          <ul class="nav child_menu">
            <li><a href="e_commerce.html">List</a></li>
          </ul>
        </li>
      </ul>
    </div> -->

  </div>
  <!-- /sidebar menu -->
</div>

core/templates/core/simple_upload.html
{% extends 'core/base.html' %}

{% load static %}

{% block contenido %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'core:index' %}">Return to home</a></p>
{% endblock contenido%}